// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-voqyrtBGdz3TVbdFKsSU6rQZ6g4Kt4I',
    appId: '1:333607680679:web:769f6875fe170200bb7982',
    messagingSenderId: '333607680679',
    projectId: 'booking-app-f38d1',
    authDomain: 'booking-app-f38d1.firebaseapp.com',
    storageBucket: 'booking-app-f38d1.appspot.com',
    measurementId: 'G-DM1XLS5Q7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlsiR-uf31vhMVQZg78ON6aXi_T2Q0VdQ',
    appId: '1:333607680679:android:d7e3b9eeb0e92374bb7982',
    messagingSenderId: '333607680679',
    projectId: 'booking-app-f38d1',
    storageBucket: 'booking-app-f38d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhBiOpQg1oOQ-xYibG5IWct8bVnmUr_oU',
    appId: '1:333607680679:ios:ac2181ddd7d8d21ebb7982',
    messagingSenderId: '333607680679',
    projectId: 'booking-app-f38d1',
    storageBucket: 'booking-app-f38d1.appspot.com',
    iosBundleId: 'com.example.ventureScape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhBiOpQg1oOQ-xYibG5IWct8bVnmUr_oU',
    appId: '1:333607680679:ios:ac2181ddd7d8d21ebb7982',
    messagingSenderId: '333607680679',
    projectId: 'booking-app-f38d1',
    storageBucket: 'booking-app-f38d1.appspot.com',
    iosBundleId: 'com.example.ventureScape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-voqyrtBGdz3TVbdFKsSU6rQZ6g4Kt4I',
    appId: '1:333607680679:web:6a5ff86ef80b724fbb7982',
    messagingSenderId: '333607680679',
    projectId: 'booking-app-f38d1',
    authDomain: 'booking-app-f38d1.firebaseapp.com',
    storageBucket: 'booking-app-f38d1.appspot.com',
    measurementId: 'G-JES778XRZJ',
  );

}